---
  kind: pipeline
  type: exec
  name: default
  
  platform:
    os: linux
    arch: amd64
  
  steps:
  - name: greeting
    when:
      branch:
        - master
    commands:
    - echo hello world