  kind: pipeline
  type: exec
  name: deploy
  
  platform:
    os: linux
    arch: amd64
  
  steps:
  - name: rsync
    commands:
    - rsync -avzh . /home/sasha/drone-test
    when:
      branch:
        - master